export { Home } from "./home";
export { QuizCategory } from "./quizCategory";
// export { QuizQuestions } from "./quizQuestionsCard";
export { Login } from "./login";
export { SignUp } from "./signup";
export { QuizComp } from "./quiz";
export { Result } from "./result";
export { QuizBoard } from "./quizBoard";
export { Rules } from "./rules";
export { Logout } from "./logout";
